development:
  dataset_id: your-project-id

production:
  dataset_id: your-project-id

test:
  # $ gcd.sh create gcd-test-dataset-directory
  # $ gcd.sh start --testing ./gcd-test-dataset-directory/
  dataset_id: gcd-test-dataset-directory
  host: http://localhost:8080/
